version: "3.7"

volumes:
  static:
  media:

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./_compose/django/Dockerfile-dev
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --no-input
        python manage.py migrate
        gunicorn --timeout=30 --workers=2 --bind 0:8000 django_app.wsgi:application
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_NAME=django_app
      - DJANGO_DB_USERNAME=django_app
      - DJANGO_DB_PASSWORD=django_app123
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_SECRET_KEY=dev_secret_key
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./_mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=django_app
      - MYSQL_USER=django_app
      - MYSQL_PASSWORD=django_app123
    networks:
      - db_network
  nginx:
    image: nginx:latest
    # ports:
    #   - "3000:8000"
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - static:/static
      - media:/media
      - ./_config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
